ALTER TABLE t_device ADD COLUMN IF NOT EXISTS latitude DOUBLE DEFAULT NULL COMMENT '纬度';
ALTER TABLE t_device ADD COLUMN IF NOT EXISTS longitude DOUBLE DEFAULT NULL COMMENT '经度';
ALTER TABLE t_device ADD COLUMN IF NOT EXISTS address VARCHAR(256) DEFAULT NULL COMMENT '详细地址';
